dist: trusty
sudo: required
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-6
      - gcc-6
script:
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  - mkdir build && cd build
  - cmake ../
  - make
  - ./stocklion_tests
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi