dist: trusty
sudo: required
language: cpp
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
before_install: sudo apt-get update -qq
install: export CXX="g++-6"
script:
  # Check versions of g++ and cmake
  - g++ -v && cmake --version
  - mkdir build && cd build
  - cmake ../
  - make
  - ./stocklion_tests