dist: trusty
sudo: required
language: cpp
compiler: gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
script:
  # Check versions of gcc, g++ and cmake
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6
  - gcc -v && g++ -v && cmake --version
  - mkdir build && cd build
  - cmake ../
  - make
  - ./stocklion_tests