dist: trusty
sudo: required
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-6
      - gcc-6
script:
  # Check versions of gcc, g++ and cmake
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6
  - gcc -v && g++ -v && cmake --version
  - mkdir build && cd build
  - cmake ../
  - make
  - ./stocklion_tests